---
  title: "Julien Saint-Vanne"
  image: "https://avatars.githubusercontent.com/u/35449860?v=4"
  description: Bioinformatic Engineer
  categories: 
    - Informatic
    - R
  about:
    template: trestles
    links: 
    - icon: twitter
      text: Twitter
      href: "https://twitter.com/workflow4metabo"
    - icon: github
      text: Github
      href: "https://github.com/jsaintvanne"
---

Young bioinformatician (yet) working on development of Shiny applications as principal activity. I love the development part of a tool because it is always a new challenge to share with diferent biologist and send them the tool that they need.

I also play a lot of volley-ball and snow volley-ball during my free time ! I'm also the happy father of a little boy since 3 months and don't sleep a lot since but I'm full of love.

## Education

**Technical certificate** in laboratory analysis in 2012

**Master degree** in BioInfomatic in 2017

## Experience

**CNRS** in Roscoff as a developper of Galaxy W4M tools for MSMS analysis (from 2018 to 2019)

**ONIRIS - LABERCA** in Nantes as a reasearch engineer in development of Shiny application for specific compounds (2020)

**EFS - UMR1236** in Rennes as a reasearch engineer to develop application to analyze multiparametric data in cytometry

**ONIRIS - LABERCA** in Nantes as a research engineer to develop Shiny application, add a visualisation part in Galaxy and make some geek things in my lab.
