---
title: "Workflow4Experimenters 2023"
date: 01/01/2023
---

Overview

   

Save the date! Analyze your data with Galaxy and the Workflow4metabolomics infrastructure!The next Workflow4Experimenters session (W4E2023) will take place in March 2023. During this one-week course (entirely in English), you will learn how to use the W4M infrastructure and analyze your own LC-MS, GC-MS, or NMR data.


 



For this new session, format changes:

• From March, 6 to 10 (10am to 12pm): online theoretical sessions (methods and tools)

Invited online speaker: Callum Martin (EMBL-EBI Metabolights, United Kingdom) 

• From March, 20 to 24 : tutoring on your own data, at Institut des systèmes complexes (Paris). Practical information - access map

Invited speaker: Helge Hecht (Masaryk University, République Tchèque)

Scientific comitee: C. Delporte (ULB, Bruxelles), C. Dalle (U.DAB IRBA, Brétigny-sur-Orge), Y. Guitton (Laberca, Nantes), C. Joly, M. Pétéra, F. Giacomoni (PFEM INRA, Clermont-Ferrand), G. Le Corguillé, (Abims, Roscoff), B. Diémé (PFEM Université Clermont Auvergne), F. Souard (ULB, Bruxelles & Université de Grenoble), C. Canlet, M. Tremblay-Franco (Toxalim INRA, Toulouse), Ralf Weber (University of Birmingham)

Agenda and preregistration: registration form (Deadline 31/12/2022)

Contact: contact@workflow4metabolomics.org

Costs: 1200€ for academic and 2500 € for private institution (to cover expenses for trainers, organization, materials and meals)
Including: Lunch, coffee break, pedagogic support and the Thursday social event. Not included: travel expenses, accommodation and 3 diners (Monday, Tuesday, Wednesday)

Target audience: LC-MS, GC-MS, NMR, FIA-MS and DI-MS experimenters (e.g. biologists, chemists).


Materials: Participants will use their laptop to perform the analysis on their W4M account. All presentations, reference datasets and workflows will be available online.


Invited speaker: Helge Hecht (Masaryk University, République Tchèque)  
 

Tutors: Each participant will be paired with a duo of tutors (preprocessing / statistics experts) who will help him/her preparing data and assist him/her during each analysis step.


Location: Institute of Complex Systems, Paris (France)
Language: English
Number of attendees: 25 max.

Sponsor : W4M est conjointement développé et maintenu par l’Institut Français de Bioinformatique (IFB, nœud Elixir) et l’Infrastructure pour la Métabolomique et la Fluxomique (MetaboHUB).

Financial support: this course received the support of the Francophone Network of Metabolomics and Fluxomics (RFMF) and of Institut des Systèmes Complexes

RFMF



See you soon in Paris!

Program (updated 22/02/2023)

Webinars 




Update! On Friday 10th Callum Martin will present  'MetaboLights: the home for metabolomics experiments and derived information'.


On-site training



For any requests, please contact the team: support * AT * workflow4metabolomics.org

Privacy policy