---
title: "Sacurine"
doi: "[publication](https://pubs.acs.org/doi/10.1021/acs.jproteome.5b00354)"
# history: "[W4M00001_Sacurine-statistics](https://workflow4metabolomics.usegalaxy.fr/published/history?id=3052e053b71f3ff5)"
uthor: "Thevenot et al."
description: "Analysis of the human adult urinary metabolome"
bibliography: "../references.bib"
galaxyref: "W4M00001"
link: "[MTBLS404](https://www.ebi.ac.uk/metabolights/editor/MTBLS404/descriptors)"
---

## Description

**Study:** 
Characterization of the physiological variations of the metabolome in biofluids is critical to understand human physiology and to avoid confounding effects in cohort studies aiming at biomarker discovery.

**Dataset:** 
In this study conducted by the MetaboHUB French Infrastructure for Metabolomics, urine samples from 184 volunteers were analyzed by reversed-phase (C18) ultrahigh performance liquid chromatography (UPLC) coupled to high-resolution mass spectrometry (LTQ-Orbitrap). A total of 258 metabolites were identified at confidence levels provided by the metabolomics standards initiative (MSI) levels 1 or 2.

**Workflow:** 
This history describes the statistical analysis of the data set from the negative ionization mode (113 identified metabolites at MSI levels 1 or 2): correction of signal drift (loess model built on QC pools) and batch effects (two batches), variable filtering (QC coefficent of variation < 30%), normalization by the sample osmolality, log10 transformation, sample filtering (Hotelling, decile and missing pvalues > 0.001) resulting in the HU_096 sample being discarded, univariate hypothesis testing of significant variations with age, BMI, or between genders (FDR < 0.05), and OPLS(-DA) modeling of age, BMI and gender.

**Comments:** 
The ‘sacurine’ data set (after normalization and filtering) is also available in the ropls R package from the Bioconductor repository. For a comprehensive analysis of the dataset (starting from the preprocessing of the raw files and including all detected features in the subsequent steps), please see the companion ‘W4M00002_Sacurine-comprehensive’ reference history.